# Generated by Django 5.1.3 on 2024-12-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_id', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=20)),
                ('catelogy_id', models.CharField(max_length=5)),
                ('dosage_form', models.CharField(max_length=10)),
                ('strength', models.CharField(max_length=10)),
                ('quantity_in_stock', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10000000)),
                ('expiry_date', models.DateField()),
            ],
        ),
    ]
